pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                script{
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/soumen321/terraform.git']])
                }
            }
        }
         stage('Initializing Terraform'){
            steps{
                script{
                    dir('terraform-jenkins-eks/EKS'){
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Formatting Terraform Code'){
            steps{
                script{
                    dir('terraform-jenkins-eks/EKS'){
                        sh 'terraform fmt'
                    }
                }
            }
        }
        stage('Validating Terraform'){
            steps{
                script{
                    dir('terraform-jenkins-eks/EKS'){
                        sh 'terraform validate'
                    }
                }
            }
        }
         stage('Previewing the Infra using Terraform'){
            steps{
                script{
                    dir('terraform-jenkins-eks/EKS'){
                        sh 'terraform plan'
                    }
                    input(message: "Are you sure to proceed?", ok: "Proceed")
                }
            }
        }
        stage('Creating/Destroying an EKS Cluster'){
            steps{
                script{
                    dir('terraform-jenkins-eks/EKS') {
                        sh 'terraform $action --auto-approve'
                    }
                }
            }
        }
        stage('Deploying Nginx application'){
            steps{
                script{
                    dir('terraform-jenkins-eks/EKS/deployment') {
                        sh 'aws eks update-kubeconfig --name my-cluster --region us-east-1'                       
                        sh 'kubectl apply -f deployment.yml'
                        sh 'kubectl apply -f service.yml'
                    }
                }
            }
        }
        
    }
}